# Generated by Django 5.2.3 on 2025-06-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Table 1, Window Table', max_length=100, unique=True)),
                ('capacity', models.IntegerField(help_text='Maximum number of people this table can seat.')),
                ('is_available', models.BooleanField(default=True, help_text='Is this table generally available for booking?')),
                ('location', models.CharField(blank=True, help_text='e.g., Main Dining Area, Terrace', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, help_text='The specific table assigned to this booking (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.table'),
        ),
    ]
